services:
  - type: web
    name: budgetory-backend
    runtime: image
    dockerfilePath: ./docker/Dockerfile
    plan: free
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE
        value: postgres
      - key: SQL_HOST
        fromDatabase:
          name: budgetory-db
          property: host
      - key: SQL_PORT
        fromDatabase:
          name: budgetory-db
          property: port
      - key: DATABASE_URL
        fromDatabase:
          name: budgetory-db
          property: connectionString
      - key: ENV_FOR_DYNACONF
        value: production

databases:
  - name: budgetory-db
    plan: free