default:
  ENVIRONMENT:
    SECRET_KEY: ~
    DEBUG: ~
    DEBUG_TOOLBAR_ENABLED: ~
    ALLOWED_HOSTS:
      - 127.0.0.1
      - localhost
  DATABASE:
    ENGINE: django.db.backends.postgresql
    NAME: budget_manager
    USER: ~
    PASSWORD: ~
    HOST: db
    PORT: 5432

production:
  dynaconf_merge: true
  ENVIRONMENT:
    DEBUG: false
    DEBUG_TOOLBAR_ENABLED: false
    ALLOWED_HOSTS:
      - .onrender.com
  DATABASE:
    ENGINE: django.db.backends.postgresql
    NAME: ~
    USER: ~
    PASSWORD: ~
    HOST: ~
    PORT: ~
